### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineers

###
GET http://localhost:8080/api/v1/software-engineers/3

###

POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Jack",
  "techStack": "HTML, CSS, JavaScript, SQL, Java"
}

###
DELETE http://localhost:8080/api/v1/software-engineers/1

###

PUT http://localhost:8080/api/v1/software-engineers/4
Content-Type: application/json

{
  "name": "Jack Scali",
  "techStack": "HTML, CSS, JavaScript, SQL, Java, React"
}